[package]
name = "poezio"
version = "0.1.0"
authors = ["Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>"]

[dependencies]
cpython = "0.2"
nom = "4"
chrono = "0.4"
ncurses = "5"
lazy_static = "1"
enum-set = "0.0"

[lib]
crate-type = ["cdylib"]
