.\" Copyright 2010 Le Coz Florent
.\" This man page is distributed under the GPLv3 license.
.\" See COPYING file
.TH "Poezio" "1" "August 1, 2010" "Poezio dev team" ""
.SH "NAME"
Poezio \- a ncurses jabber client
.SH "SYNOPSIS"
.B poezio [\-f \fICONFIG_FILE\fR] [\-h]
.SH "DESCRIPTION"
.B Poezio
is a console jabber (XMPP) client written in Python and using ncurses to draw its interface. It aims at being similar to the most famous IRC clients. For more information on XMPP see http://xmpp.org and on Poezio see http://poezio.eu
.PP
.SH "OPTIONS"
.TP
\fB\-f\fR, \fB\-\-file \fICONFIG_FILE\fR
Run gajim using \fICONFIG_FILE\fR as the config file instead of ~/.config/poezio/poezio.cfg
.TP
\fB\-h\fR
Display and help message
.SH "BUGS"
Sure, of course.
.SH "FEEDBACK"
You are encouraged to report bugs or feature requests on http://codingteam.net/project/poezio.
You can also find us on the Jabber chatroom poezio@conference.codingteam.net
.SH "AUTHORS"
Written by FLorent Le Coz <louiz@louiz.org>
