'\" t
.\"     Title: POEZIO_LOGS
.\"    Author: Tanguy Ortolo <tanguy+debian@ortolo.eu>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/28/2016
.\"    Manual: User commands
.\"    Source: Poezio
.\"  Language: English
.\"
.TH "POEZIO_LOGS" "1" "10/28/2016" "Poezio" "User commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
poezio_logs \- Display a Poezio log in a human\-readable format
.SH "SYNOPSIS"
.HP \w'\fBpoezio_logs\fR\ 'u
\fBpoezio_logs\fR [\fIoptions\fR] {\fILOG_FILE\fR}
.SH "DESCRIPTION"
.PP
Poezio
is a console\-based XMPP client\&.
.PP
\fBpoezio_logs\fR
displays a log stored in Poezio format in a more human\-readable way\&.
.SH "OPTIONS"
.PP
\fB\-i\fR, \fB\-\-hide\-info\fR
.RS 4
Hide info lines
.RE
.PP
\fB\-t\fR, \fB\-\-hide\-time\fR
.RS 4
Hide timestamps
.RE
.PP
\fB\-c\fR, \fB\-\-no\-color\fR
.RS 4
Remove color
.RE
.SH "SEE ALSO"
\fBpoezio\fR(1)
.SH "AUTHOR"
.PP
\fBTanguy Ortolo\fR <\&tanguy+debian@ortolo.eu\&>
.RS 4
Wrote this manpage for the Debian system.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2016 Tanguy Ortolo
.br
.PP
This manual page was written for the Debian system (and may be used by others).
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the Zlib License.
.sp
